// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: api/workflow-manager/workflow-manager.proto

package workflow_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkflowManager_ListFlows_FullMethodName                  = "/workflow_manager.WorkflowManager/ListFlows"
	WorkflowManager_CreateRegistration_FullMethodName         = "/workflow_manager.WorkflowManager/CreateRegistration"
	WorkflowManager_SetEmail_FullMethodName                   = "/workflow_manager.WorkflowManager/SetEmail"
	WorkflowManager_ConfirmEmail_FullMethodName               = "/workflow_manager.WorkflowManager/ConfirmEmail"
	WorkflowManager_SetRegistrationCredentials_FullMethodName = "/workflow_manager.WorkflowManager/SetRegistrationCredentials"
	WorkflowManager_CreateRestorePassword_FullMethodName      = "/workflow_manager.WorkflowManager/CreateRestorePassword"
	WorkflowManager_SetPassword_FullMethodName                = "/workflow_manager.WorkflowManager/SetPassword"
)

// WorkflowManagerClient is the client API for WorkflowManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowManagerClient interface {
	ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*ListFlowsResponse, error)
	CreateRegistration(ctx context.Context, in *CreateRegistrationRequest, opts ...grpc.CallOption) (*FlowResponse, error)
	SetEmail(ctx context.Context, in *SetEmailRequest, opts ...grpc.CallOption) (*FlowResponse, error)
	ConfirmEmail(ctx context.Context, in *ConfirmEmailRequest, opts ...grpc.CallOption) (*FlowResponse, error)
	SetRegistrationCredentials(ctx context.Context, in *SetRegistrationCredentialsRequest, opts ...grpc.CallOption) (*FlowResponse, error)
	// Create flow for restoring password
	CreateRestorePassword(ctx context.Context, in *CreateRestorePasswordRequest, opts ...grpc.CallOption) (*FlowResponse, error)
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*FlowResponse, error)
}

type workflowManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowManagerClient(cc grpc.ClientConnInterface) WorkflowManagerClient {
	return &workflowManagerClient{cc}
}

func (c *workflowManagerClient) ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*ListFlowsResponse, error) {
	out := new(ListFlowsResponse)
	err := c.cc.Invoke(ctx, WorkflowManager_ListFlows_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) CreateRegistration(ctx context.Context, in *CreateRegistrationRequest, opts ...grpc.CallOption) (*FlowResponse, error) {
	out := new(FlowResponse)
	err := c.cc.Invoke(ctx, WorkflowManager_CreateRegistration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) SetEmail(ctx context.Context, in *SetEmailRequest, opts ...grpc.CallOption) (*FlowResponse, error) {
	out := new(FlowResponse)
	err := c.cc.Invoke(ctx, WorkflowManager_SetEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) ConfirmEmail(ctx context.Context, in *ConfirmEmailRequest, opts ...grpc.CallOption) (*FlowResponse, error) {
	out := new(FlowResponse)
	err := c.cc.Invoke(ctx, WorkflowManager_ConfirmEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) SetRegistrationCredentials(ctx context.Context, in *SetRegistrationCredentialsRequest, opts ...grpc.CallOption) (*FlowResponse, error) {
	out := new(FlowResponse)
	err := c.cc.Invoke(ctx, WorkflowManager_SetRegistrationCredentials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) CreateRestorePassword(ctx context.Context, in *CreateRestorePasswordRequest, opts ...grpc.CallOption) (*FlowResponse, error) {
	out := new(FlowResponse)
	err := c.cc.Invoke(ctx, WorkflowManager_CreateRestorePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*FlowResponse, error) {
	out := new(FlowResponse)
	err := c.cc.Invoke(ctx, WorkflowManager_SetPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowManagerServer is the server API for WorkflowManager service.
// All implementations must embed UnimplementedWorkflowManagerServer
// for forward compatibility
type WorkflowManagerServer interface {
	ListFlows(context.Context, *ListFlowsRequest) (*ListFlowsResponse, error)
	CreateRegistration(context.Context, *CreateRegistrationRequest) (*FlowResponse, error)
	SetEmail(context.Context, *SetEmailRequest) (*FlowResponse, error)
	ConfirmEmail(context.Context, *ConfirmEmailRequest) (*FlowResponse, error)
	SetRegistrationCredentials(context.Context, *SetRegistrationCredentialsRequest) (*FlowResponse, error)
	// Create flow for restoring password
	CreateRestorePassword(context.Context, *CreateRestorePasswordRequest) (*FlowResponse, error)
	SetPassword(context.Context, *SetPasswordRequest) (*FlowResponse, error)
	mustEmbedUnimplementedWorkflowManagerServer()
}

// UnimplementedWorkflowManagerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkflowManagerServer struct {
}

func (UnimplementedWorkflowManagerServer) ListFlows(context.Context, *ListFlowsRequest) (*ListFlowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFlows not implemented")
}
func (UnimplementedWorkflowManagerServer) CreateRegistration(context.Context, *CreateRegistrationRequest) (*FlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRegistration not implemented")
}
func (UnimplementedWorkflowManagerServer) SetEmail(context.Context, *SetEmailRequest) (*FlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEmail not implemented")
}
func (UnimplementedWorkflowManagerServer) ConfirmEmail(context.Context, *ConfirmEmailRequest) (*FlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmEmail not implemented")
}
func (UnimplementedWorkflowManagerServer) SetRegistrationCredentials(context.Context, *SetRegistrationCredentialsRequest) (*FlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRegistrationCredentials not implemented")
}
func (UnimplementedWorkflowManagerServer) CreateRestorePassword(context.Context, *CreateRestorePasswordRequest) (*FlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestorePassword not implemented")
}
func (UnimplementedWorkflowManagerServer) SetPassword(context.Context, *SetPasswordRequest) (*FlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (UnimplementedWorkflowManagerServer) mustEmbedUnimplementedWorkflowManagerServer() {}

// UnsafeWorkflowManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowManagerServer will
// result in compilation errors.
type UnsafeWorkflowManagerServer interface {
	mustEmbedUnimplementedWorkflowManagerServer()
}

func RegisterWorkflowManagerServer(s grpc.ServiceRegistrar, srv WorkflowManagerServer) {
	s.RegisterService(&WorkflowManager_ServiceDesc, srv)
}

func _WorkflowManager_ListFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).ListFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowManager_ListFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).ListFlows(ctx, req.(*ListFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_CreateRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).CreateRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowManager_CreateRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).CreateRegistration(ctx, req.(*CreateRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_SetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).SetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowManager_SetEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).SetEmail(ctx, req.(*SetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_ConfirmEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).ConfirmEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowManager_ConfirmEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).ConfirmEmail(ctx, req.(*ConfirmEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_SetRegistrationCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRegistrationCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).SetRegistrationCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowManager_SetRegistrationCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).SetRegistrationCredentials(ctx, req.(*SetRegistrationCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_CreateRestorePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestorePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).CreateRestorePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowManager_CreateRestorePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).CreateRestorePassword(ctx, req.(*CreateRestorePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowManager_SetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).SetPassword(ctx, req.(*SetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowManager_ServiceDesc is the grpc.ServiceDesc for WorkflowManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow_manager.WorkflowManager",
	HandlerType: (*WorkflowManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFlows",
			Handler:    _WorkflowManager_ListFlows_Handler,
		},
		{
			MethodName: "CreateRegistration",
			Handler:    _WorkflowManager_CreateRegistration_Handler,
		},
		{
			MethodName: "SetEmail",
			Handler:    _WorkflowManager_SetEmail_Handler,
		},
		{
			MethodName: "ConfirmEmail",
			Handler:    _WorkflowManager_ConfirmEmail_Handler,
		},
		{
			MethodName: "SetRegistrationCredentials",
			Handler:    _WorkflowManager_SetRegistrationCredentials_Handler,
		},
		{
			MethodName: "CreateRestorePassword",
			Handler:    _WorkflowManager_CreateRestorePassword_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _WorkflowManager_SetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/workflow-manager/workflow-manager.proto",
}
